grails-app/domain/fr/mbds/grails/User.groovy
package fr.mbds.grails

import groovy.transform.EqualsAndHashCode
import groovy.transform.ToString
import grails.compiler.GrailsCompileStatic

@GrailsCompileStatic
@EqualsAndHashCode(includes='username')
@ToString(includes='username', includeNames=true, includePackage=false)
class User implements Serializable {

    private static final long serialVersionUID = 1

    String username
    String password
    boolean enabled = true
    boolean accountExpired
    boolean accountLocked
    boolean passwordExpired

    Set<Role> getAuthorities() {
        (UserRole.findAllByUser(this) as List<UserRole>)*.role as Set<Role>
    }

    static hasMany = [annonces: Annonce]

    static constraints = {
        password nullable: false, blank: false, password: true
        username nullable: false, blank: false, unique: true
    }

    static mapping = {
	    password column: '`password`'
    }
}

grails-app/controllers/fr/mbds/grails/UserController.groovy
package fr.mbds.grails

import grails.plugin.springsecurity.annotation.Secured
import grails.validation.ValidationException
import static org.springframework.http.HttpStatus.*

@Secured(value=["hasRole('ROLE_ADMIN')"])
class UserController {
    UserService userService
    static allowedMethods = [save: "POST", update: "PUT", delete: "DELETE"]

    def index(Integer max) {
        params.max = Math.min(max ?: 10,100)
        respond userService.list(params), model:[userCount: userService.count()]
    }

    def show(Long id) {
        respond userService.get(id)
    }

    def create() {
        respond new User(params)
    }

    def save(User user) {
        if (user == null) {
            notFound()
            return
        }

        try {
            userService.save(user)
        } catch (ValidationException e) {
            respond user.errors, view:'create'
            return
        }

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.created.message', args: [message(code: 'user.label', default: 'User'), user.id])
                redirect user
            }
            '*' { respond user, [status: CREATED] }
        }
    }

    def edit(Long id) {
        respond userService.get(id)
    }

    def update(User user) {
        if (user == null) {
            notFound()
            return
        }

        try {
            userService.save(user)
        } catch (ValidationException e) {
            respond user.errors, view:'edit'
            return
        }
        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.updated.message', args: [message(code: 'user.label', default: 'User'), user.id])
                redirect user
            }
            '*'{ respond user, [status: OK] }
        }
    }

    def delete(Long id) {
        if (id == null) {
            notFound()
            return
        }

        userService.delete(id)

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.deleted.message', args: [message(code: 'user.label', default: 'User'), id])
                redirect action:"index", method:"GET"
            }
            '*'{ render status: NO_CONTENT }
        }
    }
    protected void notFound() {
        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.not.found.message', args: [message(code: 'user.label', default: 'User'), params.id])
                redirect action: "index", method: "GET"
            }
            '*'{ render status: NOT_FOUND }
        }
    }
}

grails-app/views/user/create.gsp
<!DOCTYPE html>
<html>
    <head>
        <meta name="layout" content="header" />
        <g:set var="entityName" value="${message(code: 'user.label', default: 'User')}" />
        <title><g:message code="default.create.label" args="[entityName]" /></title>
        <style>
        li{
        list-style:none;
        margin-left:0;
        padding-left:0;

        }

        </style>
    </head>
    <body>
    <div class="span9">
        <div class="content">
            <div class="module">
                <div class="module-head">
                    <h3>Utilisateur
                        <g:link controller="user" action="index"  class="btn btn-small btn-info">
                            <span class="icon icon-list"> </span>
                            Liste des utilisateurs
                        </g:link>
                    </h3>
                </div>
                <div class="stream-list">
                    <div class="media stream new-update">
                        <a href="#">
                            Création d'utilisateur
                        </a>
                    </div>
                    <div class="media stream">
                        <a href="#" class="media-avatar medium pull-left">
                            <asset:image src="images/user.png"/>
                        </a>
                        <div class="media-body">
                            <div class="stream-headline">
                                <g:if test="${flash.message}">
                                    <div class="message" role="status">${flash.message}</div>
                                </g:if>
                                <g:hasErrors bean="${this.user}">
                                    <ul class="errors" role="alert">
                                        <g:eachError bean="${this.user}" var="error">
                                            <li <g:if test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>><g:message error="${error}"/></li>
                                        </g:eachError>
                                    </ul>
                                </g:hasErrors>
                                <g:form resource="${this.user}" method="POST" >
                                    <fieldset class="form">
                                        <f:all bean="user"/>
                                    </fieldset>
                                    <fieldset class="buttons">
                                        <g:submitButton name="create" class="btn btn-success" value="${message(code: 'default.button.create.label', default: 'Créer')}" />
                                    </fieldset>
                                </g:form>
                                </div>
                            </div><!--/.stream-headline-->

                        </div>
                    </div><!--/.media .stream-->
                </div><!--/.stream-list-->

            </div><!--/.module-body-->
        </div><!--/.module-->




    </body>
</html>

grails-app/views/user/edit.gsp
<!DOCTYPE html>
<html>
    <head>
        <meta name="layout" content="header" />
        <g:set var="entityName" value="${message(code: 'user.label', default: 'User')}" />
        <title><g:message code="default.edit.label" args="[entityName]" /></title>
        <style>
        li{
            list-style:none;
            margin-left:0;
            padding-left:0;
        }
        </style>
    </head>
    <body>

    <div class="span9">
        <div class="content">
            <div class="module">
                <div class="module-head">
                    <h3>Utilisateur
                        <g:link controller="user" action="index"  class="btn btn-small btn-info">
                            <span class="icon icon-list"> </span>
                            Liste des utilisateurs
                        </g:link>
                    </h3>
                </div>
                <div class="stream-list">
                    <div class="media stream new-update">
                        <a href="#">
                            Modification d'utilisateur
                        </a>
                    </div>
                    <div class="media stream">
                        <a href="#" class="media-avatar medium pull-left">
                            <asset:image src="images/user.png"/>
                        </a>
                        <div class="media-body">
                            <div class="stream-headline">
                                <g:if test="${flash.message}">
                                    <div class="message" role="status">${flash.message}</div>
                                </g:if>
                                <g:hasErrors bean="${this.user}">
                                    <ul class="errors" role="alert">
                                        <g:eachError bean="${this.user}" var="error">
                                            <li <g:if test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>><g:message error="${error}"/></li>
                                        </g:eachError>
                                    </ul>
                                </g:hasErrors>
                                <g:form resource="${this.user}" method="PUT">
                                    <g:hiddenField name="version" value="${this.user?.version}" />
                                    <fieldset class="form">
                                        <f:all bean="user"/>
                                    </fieldset>
                                    <fieldset class="buttons">
                                        <input class="save btn btn-success" type="submit" value="Modifier" />
                                    </fieldset>
                                </g:form>
                            </div>
                        </div><!--/.stream-headline-->

                    </div>
                </div><!--/.media .stream-->
            </div><!--/.stream-list-->

        </div><!--/.module-body-->
    </div><!--/.module-->
    </body>
</html>

grails-app/views/user/index.gsp
<!DOCTYPE html>
<html>
<head>
    <meta name="layout" content="header"/>
    <g:set var="entityName" value="${message(code: 'user.label', default: 'User')}"/>
    <title><g:message code="default.list.label" args="[entityName]"/></title>
    <style>
    li{
        list-style:none;
        margin-left:0;
        padding-left:0;
    }
    </style>
</head>
<body>
<div class="span9">
    <div class="content">
        <div class="module">
            <div class="module-head">
                <h3>Liste des utilisateurs</h3>
            </div>
            <div class="module-option clearfix">
                <form>
                    <div class="input-append pull-left">
                        <input type="text" class="span3" placeholder="username...">
                        <button type="submit" class="btn">
                            <i class="icon-search"></i>
                        </button>
                    </div>
                </form>
                <div class="btn-group pull-right" data-toggle="buttons-radio">
                    <g:link controller="user" action="create">
                    <button type="button" class="btn btn-success">
                        <i class="icon icon-plus"></i>

                            Ajouter utilisateur
                    </button>
                    </g:link>
                    <button type="button" class="btn">
                        Tous les utilisateurs</button>
                    <button type="button" class="btn">
                        Admin</button>
                    <button type="button" class="btn">
                        Moderateur</button>
                    <button type="button" class="btn">
                        Client</button>
                </div>
            </div>
            <div class="module-body">
                <div class="row-fluid">
                    <g:each in="${userList}" var="user">
                    <div class="span2">
                       <div class="media user">
                        <g:link controller="user" action="show" id="${user.id}">
                                 <asset:image src="images/user.png"/>
                        </g:link>
                            <div class="media-body">
                                <h3 class="media-title">
                                    ${user.username}
                                </h3>
                                <p>
                                <div class="media-option btn-group shaded-icon">
                                     <g:link controller="user" action="show" id="${user.id}" class="btn btn-small  btn-info">
                                        <i class="icon-eye-open" style="color: white;"></i>
                                      </g:link>
                                </div>
                           <div class="media-option btn-group shaded-icon">
                               <g:link controller="user" action="edit" id="${user.id}" class="btn btn-small  btn-success">
                                   <i class="icon-pencil" style="color: white;"></i>
                               </g:link>
                           </div>
                            </div>
                        </div>
                    </div>
                      </g:each> 
           </div>
         </div>
       </div>
    </div>
</div>
</body>
</html>

grails-app/views/user/show.gsp
<!DOCTYPE html>
<html>
    <head>
        <meta name="layout" content="header" />
        <g:set var="entityName" value="${message(code: 'user.label', default: 'User')}" />
        <title><g:message code="default.show.label" args="[entityName]" /></title>

        <style>
        li{
            list-style:none;
            margin-left:0;
            padding-left:0;
        }

        </style>
    </head>
    <body>
    <div class="span9">
        <div class="content">
        <div class="nav" role="navigation">
            <ul>
                <li><g:link class="list btn btn-info" action="index"><i class="icon icon-list"></i>Liste des utilisateurs</g:link></li>
                <p></p>
                <li><g:link class="create btn btn-info" action="create"><i class="icon icon-plus"></i>Ajouter un utilisateur</g:link></li>
            </ul>
        </div>
        <div id="show-user" class="content scaffold-show" role="main">

            <h1>Information sur l'utilisateur</h1>
            <g:link controller="user" action="show" id="${user.id}">
                <asset:image src="images/user.png"/>
            </g:link>
            <g:if test="${flash.message}">
            <div class="message" role="status">${flash.message}</div>
            </g:if>
            <table cellpadding="0" cellspacing="0" border="0" class="datatable-1 table table-bordered table-striped	 display"
                   width="100%">
                <tbody>
                <tr>
                <th>
                    Nom d'utilisateur
                </th>
                    <th>
                    Compte activé
                    </th>
                    <th>
                        Compte bloqué
                    </th>
                    <th>
                        Annonces
                    </th>
                </tr>

                <tr>
                    <td> ${user.username}</td>
                    <td><g:if test="${user.enabled}">oui
                    </g:if>
                    <g:else>
                        non
                    </g:else>
                    </td>
                    <td><g:if test="${! user.accountLocked}">non
                    </g:if>
                    <g:else>oui</g:else>
                    </td>
                    <td>
                        <g:each in="${user.annonces}" var="annonce">
                            <li>
                                <g:link controller="annonce" action="show" id="${annonce.id}">
                                    ${annonce.title}
                                </g:link>
                            </li>
                        </g:each>
                    </td>
                </tr>

                </tbody>
            </table>
        </div>
            <p></p>
            <g:form resource="${this.user}" method="DELETE">
                <fieldset class="buttons">
                    <g:link class="edit icon icon-pencil  btn btn-success" action="edit" resource="${this.user}"></g:link>
                    <input class="btn btn-danger" type="submit" value="Supprimer" onclick="return confirm('${message(code: 'default.button.delete.confirm.message', default: 'Are you sure?')}');" />
                </fieldset>
            </g:form>
        </div>
        </div>
    </div>
    </body>
</html>